<?php

namespace DC\TenisBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class GameController__JMSInjector
{
    public static function inject($container) {
        $instance = new \DC\TenisBundle\Controller\GameController();
        return $instance;
    }
}
